-- 코드를 입력하세요
  WITH TBL_ROWNUM 
    AS (SELECT NAME
             , ROW_NUMBER() OVER(ORDER BY DATETIME) AS "ROWNUMBER"
          FROM ANIMAL_INS
       )
SELECT NAME
  FROM TBL_ROWNUM
 WHERE ROWNUMBER = 1;